<?php

namespace App\Forms;

use Cake\Form\Schema;
use Cake\ORM\Locator\LocatorAwareTrait;
use Cake\Validation\Validator;

class NewUserForm extends \Cake\Form\Form
{

    use LocatorAwareTrait;

    public function setSchema(Schema $schema)
    {
        $schema
            ->addField('email', ['type' => 'text'])
            ->addField('new_customer', ['type' => 'text'])
            ->addField('customers', ['type' => 'text']);

        return parent::setSchema($schema);
    }

    public function validationDefault(Validator $validator): Validator
    {
        $validator->notEmptyString('email', true, '`email` is required');
//        return $validator;

        return parent::validationDefault($validator);
    }


    public function setErrors(array $errors)
    {
        return parent::setErrors($errors); // TODO: Change the autogenerated stub
    }

    public function execute(array $data, array $options = []): bool
    {
        return parent::execute($data, $options); // TODO: Change the autogenerated stub
    }

    public function setData(array $data)
    {
        return parent::setData($data); // TODO: Change the autogenerated stub
    }

}
