<?php

namespace App\Forms;

use Cake\Form\Schema;

class NewUserForm extends \Cake\Form\Form
{
    public function setSchema(Schema $schema)
    {
        $schema
            ->addField('email', ['type' => 'text'])
            ->addField('new_customer', ['type' => 'text'])
            ->addField('customers', ['type' => 'text']);

        return parent::setSchema($schema);
    }

    public function validate(array $data, ?string $validator = null): bool
    {
        return parent::validate($data, $validator); // TODO: Change the autogenerated stub
    }

    public function setErrors(array $errors)
    {
        return parent::setErrors($errors); // TODO: Change the autogenerated stub
    }

    public function execute(array $data, array $options = []): bool
    {
        return parent::execute($data, $options); // TODO: Change the autogenerated stub
    }

    public function setData(array $data)
    {
        return parent::setData($data); // TODO: Change the autogenerated stub
    }

}
